### PR TITLE
Add support for package auto-discovery

### PR DESCRIPTION
**Pull request by pawelmysior**

### CODE REVIEW

**Comment by PawelMysior** [comment]
Not sure why the build doesn't pass. The problem is with the line 127 of the spec, which is:

```
expect($this->post->lockedUntil())->toEqual(Carbon::now()->addMinutes(5)->toDateTimeString());
```

my PR should not make this fail. And there are 4 similar assertions that pass without any problem.

Maybe it would be beneficial to always compare string values or timestamps?

```
expect($this->post->lockedUntil()->toDateTimeString())->toEqual(Carbon::now()->addMinutes(5)->toDateTimeString());

// or

expect($this->post->lockedUntil()->timestamp)->toEqual(Carbon::now()->addMinutes(5)->timestamp);
```

**Comment by PawelMysior** [comment]
Hey @jarektkaczyk, would you consider merging this in?

**Comment by jarektkaczyk** [comment]
thx, sry for ages it took to merge :+1:

**Comment by pawelmysior** [comment]
No problem, thanks 👍

**Pull request merged**
